### ISSUE TITLE
Unknown CMake command "NVCUDA_COMPILE_PTX"

### ISSUE THREAD

**Issue by clemenswasser** [nvpro-samples/build_all#1]
run `./clone_all.sh`
run `cmake .` -> error `Unknown CMake command "NVCUDA_COMPILE_PTX"`

Complete log

[clemens@clemens-laptop build_all]$ cmake .
-- BASE_DIRECTORY = /home/clemens/cmp/build_all/..
-- CMAKE_CURRENT_SOURCE_DIR = /home/clemens/cmp/build_all
-- found Glew source code. Using it instead of library
-- using GLFW library /lib/libglfw.so
-- -------------------------------
-- Processing Project gl_cadscene_rendertechniques:
-- --> using package NSight
-- --> using package AntTweakBar
-- --> using package ZLIB
CMake Warning (dev) at /home/clemens/cmp/shared_sources/CMakeLists_include.txt:186 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable ZLIB_ROOT is set to:

    /home/clemens/cmp/build_all/../shared_external/zlib

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  /home/clemens/cmp/gl_cadscene_rendertechniques/CMakeLists.txt:39 (_add_package_ZLIB)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- -------------------------------
-- Processing Project gl_cl_interop_pingpong_st:
-- --> using package NSight
-- --> using package AntTweakBar
-- --> using package OpenCL : /usr/lib/libOpenCL.so
-- -------------------------------
-- Processing Project gl_commandlist_basic:
-- --> using package NSight
-- --> using package AntTweakBar
-- -------------------------------
-- Processing Project gl_commandlist_bk3d_models:
-- --> package SvcMFCUI not available under Unix
-- --> using package AntTweakBar
-- --> using package OpenGLText
-- --> using package ZLIB
CMake Warning (dev) at /home/clemens/cmp/shared_sources/CMakeLists_include.txt:186 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable ZLIB_ROOT is set to:

    /home/clemens/cmp/build_all/../shared_external/zlib

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  /home/clemens/cmp/gl_commandlist_bk3d_models/CMakeLists.txt:53 (_add_package_ZLIB)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- -------------------------------
-- Processing Project gl_cuda_interop_pingpong_st:
-- --> using package NSight
-- --> using package AntTweakBar
-- --> using package CUDA
CMake Error at /home/clemens/cmp/gl_cuda_interop_pingpong_st/CMakeLists.txt:54 (NVCUDA_COMPILE_PTX):
  Unknown CMake command "NVCUDA_COMPILE_PTX".

-- Configuring incomplete, errors occurred!
See also "/home/clemens/cmp/build_all/CMakeFiles/CMakeOutput.log".
See also "/home/clemens/cmp/build_all/CMakeFiles/CMakeError.log".

**Comment by pixeljetstream** [comment]
closing, as framework has changed a lot
