### ISSUE TITLE
installation failure (dx12_present_barrier)

### ISSUE THREAD

**Issue by kyamant** [nvpro-samples/build_all#5]
installation failed due to **DX12SDK**  not being present.
DX12SDK  has been end-of-lifed, WindowsSDK is used from windows 7 forward!
What are these supposed to be for a contemporary(!) installation?
**Could NOT find DX12SDK (missing: DX12SDK_INCLUDE_DIR DX12SDK_LIBRARY_DIR
  DX12SDK_D3D_LIBRARIES)**
```
-- -------------------------------
-- Processing Project dx12_present_barrier:
-- BASE_DIRECTORY = D:/Personal/Projects/ProjNvProSamples
-- CMAKE_CURRENT_SOURCE_DIR = D:/Personal/Projects/ProjNvProSamples/dx12_present_barrier
CMake Error at D:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find DX12SDK (missing: DX12SDK_INCLUDE_DIR DX12SDK_LIBRARY_DIR
  DX12SDK_D3D_LIBRARIES)
Call Stack (most recent call first):
  D:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  D:/Personal/Projects/ProjNvProSamples/nvpro_core/cmake/find/FindDX12SDK.cmake:43 (find_package_handle_standard_args)
  D:/Personal/Projects/ProjNvProSamples/nvpro_core/cmake/setup.cmake:546 (find_package)
  CMakeLists.txt:35 (_add_package_DirectX12)


-- Configuring incomplete, errors occurred!
```

**Comment by NBickford-NV** [comment]
Hi @kyamant ! I believe we fixed this in https://github.com/nvpro-samples/nvpro_core/commit/1b5ff608551a68f2ed86848ad81dd40debdba682#diff-f8bb9a3b29490f37f95a9e26de724066547f57190122076b2fb359d8a50e807a by replacing `nvpro_core/cmake/find/FindDX12SDK.cmake`, which previously searched for the Direct3D 12 headers and libraries within the Windows SDK. I believe we now make use of the DirectX headers in the `nvpro_core/third_party/dxh` submodule together with Visual Studio's built-in support for finding dxgi.lib and d3d12.lib.

Thanks!
