### ISSUE TITLE
few more libs need in Linux prerequisites section of readme

### ISSUE THREAD

**Issue by ayaromenok** [nvpro-samples/build_all#7]
`libglm-dev libpng-dev libfreeimage-dev`

**Comment by NBickford-NV** [comment]
Hi @ayaromenok, thank you for the bug report!

I can confirm that `libglm-dev` and `libfreeimage-dev` should be installed. Do you happen to know which project requires `libpng-dev`? The only project in our team that uses the libpng headers I know of is the [DMM Toolkit](https://github.com/NVIDIAGameWorks/Displacement-MicroMap-Toolkit), which is outside the nvpro-samples and has its own package installation list.

Thank you!

**Comment by NBickford-NV** [comment]
Answering this question: It looks like `gl_vk_chopper` uses libpng. Since nvpro_core has stb_image, I may look at modifying gl_vk_chopper to remove this dependency.

**Comment by ayaromenok** [comment]
Sorry - my bad that not write a name of projects which required that dependencies. Thank you for update.

**Comment by NBickford-NV** [comment]
Hi @ayaromenok ! We've updated gl_vk_chopper to remove its LibPNG and Assimp dependencies, and I've added libglm-dev and libfreeimage-dev to the list of Linux dependencies in https://github.com/nvpro-samples/build_all/commit/bbbff7336ba1254d01b9126841018b2c7766731f. Thanks again!
